version: '3.8'

services:
  medical-chatbot:
    build: .
    ports:
      - "8501:8501"
      - "11434:11434"
    volumes:
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

volumes:
  ollama_data: